---
title: "Project"
author: "Linh Le"
date: "April 23, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Fitting Seasonal Means Model
```{r}
library(tseries)
library(TSA)

#ridership-average monthly ridership
dat <- read.csv("C:/Users/Linh/Desktop/Math/Stat/STAT 520/Assignments/portland.csv", header=TRUE)

#split 5 last obs
forecast <- dat[110:114,]
ride <- dat[1:109,]$Ridership
dat <- dat[1:109,]$Ridership
forecast

#plot time series
data <- ts(ride, frequency=12, start=c(1960,1))
plot(data, type='l', xlab='Time', ylab='Total Number of Riders')
points(y=ride, x=as.vector(time(data)), pch=as.vector(season(data)))


```

```{r}
month.=season(data)
mod=lm(data~month.-1)
summary(mod)

qqnorm(rstudent(mod)); qqline(rstudent(mod))
hist(rstudent(mod),xlab='Standardized Residuals')

shapiro.test(rstudent(mod))

runs(rstudent(mod))
```

```{r}
ts.plot(data, fitted(mod), color=c('red','blue'))
```

```{r}
plot(y=rstudent(mod), x=as.vector(time(data)), type='o')
abline(0,0)
```




```{r}
acf(rstudent(mod), lag.max=40)
```



\bigskip\bigskip
Fitting ARIMA model
```{r}
adf.test(data)
#non-stationary

acf = acf(as.factor(data), lag.max=40)
pacf = pacf(as.factor(data), lag.max=40)
eacf(data)
```

```{r}
# difference
ts.diff <- diff(data)
plot(ts.diff, main="First Difference")
adf.test(ts.diff)
acf(as.factor(ts.diff), lag.max=40)
pacf(as.factor(ts.diff), lag.max=40)
eacf(ts.diff)
```

```{r}
ari <- arima(data, order=c(0,1,2), method='ML')
arii <- arima(data, order=c(1,1,2), method='ML')

ari
arii 

qqnorm(residuals(ari)) ; qqline(residuals(ari))
hist(residuals(ari),xlab='Standardized Residuals')


qqnorm(residuals(arii)) ; qqline(residuals(ari))
hist(residuals(arii),xlab='Standardized Residuals')

```
```{r}
shapiro.test(residuals(ari))
```

```{r}
ts.plot(zlag(data), data-residuals(ari), color=c('red','blue'))
```
```{r}
tsdiag(ari)
```
```{r}
# overfit

ari=arima(data, order=c(0,1,2), method='ML')
ari1=arima(data, order=c(0,1,3), method='ML')
ari
ari1
```


```{r}
# forecast
p1=plot(ari, n.ahead=5)
pred1=cbind(p1$lpi, p1$pred, p1$upi, forecast$Ridership)
pred1
```

